Скелет нейронки


1) инициализация — задание количества входных, скрытых и выходных узлов;
2) тренировка — уточнение весовых коэффициентов в процессе
обработки предоставленных для обучения сети тренировочных
примеров;
3) опрос — получение значений сигналов с выходных узлов после
предоставления значений входящих сигналов.

In [ ]:
# определение класса нейронной сети
class neuralNetwork:
# инициализировать нейронную сеть
   def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
# задать количество узлов во входном, скрытом и выходном слое
     self.inodes = inputnodes#вход
     self.hnodes = hiddennodes#скрытом
     self.onodes = outputnodes#выходном
# коэффициент обучения
     self.lr = learningrate
     pass
# тренировка нейронной сети
   def train():
     pass
# опрос нейронной сети
   def query():
     pass


In [ ]:
# количество входных, скрытых и выходных узлов
input_nodes = 3
hidden_nodes = 3
output_nodes = 3
# коэффициент обучения равен 0,3
learning_rate = 0.3
# создать экземпляр нейронной сети
n = neuralNetwork(input_nodes,hidden_nodes,output_nodes,learning_rate)

Весовые коэффициенты — сердце сети

In [2]:
import numpy
numpy.random.rand(3, 3)-0.5

array([[ 0.40367325, -0.39021633,  0.09366221],
       [-0.25245908,  0.2850796 , -0.33672615],
       [-0.12775591,  0.48625431, -0.26498132]])

In [3]:
# Матрицы весовых коэффициентов связей wih (между входным и скрытым
# слоями) и who (между скрытым и выходным слоями).
# Весовые коэффициенты связей между узлом i и узлом j следующего слоя
# обозначены как w_i_j:
# wll w21
# wl2 w22 и т.д.


#self.wih = (numpy.random.rand(self.hnodes, self.inodes) - 0.5)
#self.who = (numpy.random.rand(self.onodes, self.hnodes) - 0.5)

self.wih = numpy.random.normal(0.0, pow(self.hnodes, -0.5),(self.hnodes, self.inodes))
self.who = numpy.random.normal(0.0, pow(self.onodes, -0.5),(self.onodes, self.hnodes))

NameError: name 'self' is not defined

In [ ]:
hidden_inputs = numpy.dot(self.wih, inputs)


In [ ]:
# библиотека scipy.special содержит сигмоиду expit()
import scipy.special

# использование сигмоиды в качестве функции активации
self.activation_function = lambda x: scipy.special.expit(x)


# рассчитать исходящие сигналы для скрытого слоя
hidden_outputs = self.activation_function(hidden_inputs)


всё вместе

In [ ]:
# рассчитать входящие сигналы для скрытого слоя
hidden_inputs = numpy.dot(self.wih, inputs)
# рассчитать исходящие сигналы для скрытого слоя
hidden_outputs = self.activation_function(hidden_inputs)
# рассчитать входящие сигналы для выходного слоя
final_inputs = numpy.dot(self.who, hidden_outputs)
# рассчитать исходящие сигналы для выходного слоя
final_outputs = self.activation_function(final_inputs)


Текущее состояние кода стр 168

In [3]:
import numpy
# библиотека scipy.special с сигмоидой expit ()
import scipy.special


# определение класса нейронной сети
class neuralNetwork:
    # инициализировать нейронную сеть
    def __init__(self, inputnodes, hiddennodes, outputnodes,learningrate):
        # задать количество узлов во входном, скрытом и выходном слое
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        # Матрицы весовых коэффициентов связей wih и who.
        # Весовые коэффициенты связей между узлом i и узлом j
        # следующего слоя обозначены как w__i__j:
        # wll w21
        # wl2 w22 и т.д.
        self.wih = numpy.random.normal(0.0, pow(self.hnodes, -0.5),(self.hnodes, self.inodes))
        self.who = numpy.random.normal(0.0, pow(self.onodes, -0.5),(self.onodes, self.hnodes))
        # коэффициент обучения
        self.lr = learningrate
        # использование сигмоиды в качестве функции активации
        self.activation_function = lambda x: scipy.special.expit(x)
        pass
    # тренировка нейронной сети
    def train (self, inputs_list, targets_list) :
        # преобразование списка входных значений
        # в двухмерный массив
        inputs = numpy.array(inputs_list, ndmin=2).T
        targets = numpy.array(targets_list, ndmin=2).T
        # рассчитать входящие сигналы для скрытого слоя
        hidden_inputs = numpy.dot(self.wih, inputs)
        # рассчитать исходящие сигналы для скрытого слоя
        hidden_outputs = self.activation_function(hidden_inputs)
        # рассчитать входящие сигналы для выходного слоя
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # рассчитать исходящие сигналы для выходного слоя
        final_outputs = self.activation_function(final_inputs)

        # ошибки выходного слоя =
        # (целевое значение - фактическое значение)
        output_errors = targets - final_outputs
        # ошибки скрытого слоя - это ошибки output_errors,
        # распределенные пропорционально весовым коэффициентам связей
        # и рекомбинированные на скрытых узлах
        hidden_errors = numpy.dot(self.who.T, output_errors)

        # обновить весовые коэффициенты для связей между
        # скрытым и выходным слоями
        self.who += self.lr * numpy .dot ((output_errors *final_outputs * (1.0 - final_outputs)),numpy.transpose (hidden_outputs))
        # обновить весовые коэффициенты для связей между
        # входным и скрытым слоями
        self.wih += self.lr * numpy.dot((hidden_errors *hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))






        pass
    # опрос нейронной сети
    def query(self, inputs_list):
        # преобразовать список входных значений в двухмерный массив
        inputs = numpy.array(inputs_list, ndmin=2).T
        # рассчитать входящие сигналы для скрытого слоя
        hidden_inputs = numpy.dot(self.wih, inputs)
        # рассчитать исходящие сигналы для скрытого слоя
        hidden_outputs = self.activation_function(hidden_inputs)
        # рассчитать входящие сигналы для выходного слоя
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # рассчитать исходящие сигналы для выходного слоя
        final_outputs = self.activation_function(final_inputs)

        return final_outputs



In [4]:
input_nodes = 3
hidden_nodes = 3
output_nodes = 3
# коэффициент обучения равен 0,3
learning_rate = 0.3
# создать экземпляр нейронной сети
n=neuralNetwork(input_nodes,hidden_nodes,output_nodes,learning_rate)
n.query([1.0,0.5,-1.5])

(array([[ 1. ],
        [ 0.5],
        [-1.5]]),
 array([[-0.54139306, -0.15587393, -0.20562253],
        [-0.13241335, -0.21628478, -0.52547743],
        [ 0.81590875, -0.09033497,  0.03655086]]),
 array([[-0.31089622],
        [ 0.5476604 ],
        [ 0.71591497]]),
 <function __main__.neuralNetwork.__init__.<locals>.<lambda>(x)>,
 array([[0.422896  ],
        [0.63359262],
        [0.67170683]]),
 array([[-0.81828669],
        [ 0.41938428],
        [-0.58094436]]),
 <function __main__.neuralNetwork.__init__.<locals>.<lambda>(x)>,
 array([[0.30612747],
        [0.60333591],
        [0.35871533]]))